music_directory		"/home/men/Music"
playlist_directory	"/home/men/Music/Playlists"

bind_to_address		"127.0.0.1" # localhost
#port				"6600"

# Suppress all messages below the given threshold.  Use "verbose" for
# troubleshooting. Available setting arguments are "notice", "info", "verbose",
# "warning" and "error".
#
#log_level					 "notice"

restore_paused			"yes"
auto_update				"yes"
#auto_update_depth		"3"

#follow_outside_symlinks	"yes"
#follow_inside_symlinks		"yes"

audio_output {
	type		"pipewire"
	name		"PipeWire Sound Server"
#	mixer_type   "none"			# optional
}

#filesystem_charset		"UTF-8"
